### ISSUE TITLE
[Enhancement] Trait Inheritance

### ISSUE THREAD

**Issue by baskren** [eugenie32b/smarttraits#1]
First - a most awesome project.  I've been looking for something like this for a very long time and never had the time to write it myself.

Have you considered the use case of inheritance for Traits?  For example, starting with **Stage4** in the **SmartTraits.Demo** project, if I were to add the following:

#### PersonalAddressTrait.cs

```csharp
    [Trait]
    abstract partial class PersonalAddressTrait : AddressTrait, IName, IAddress
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        [Overrideable]
        public string GetFullName()
        {
            return $"{GetNamePrefix()} {FirstName} {LastName}";
        }

       public string GetFullAddress()
        {
            return $"{GetNamePrefix()} {FirstName} {LastName} \n {Address} \n {City}, {State} \t {ZipCode}";
        }

        [TraitIgnore]
        private string GetNamePrefix()
        {
            return null;
        }
    }
```

Notice that `GetFullAddress()` uses properties from both **PersonalAddressTrait** and **AddressTrait**.

#### ExampleC.cs

```csharp
    [AddTrait(typeof(PersonalAddressTrait))]
    partial class ExampleC : BaseC, IName, IAddress
    {
        public string MiddleName { get; set; }

        private string GetNamePrefix()
        {
            return "sir/madam ";
        }

        public string GetLabel()
        {
            return "Address Label: ";
        }

        public string GetFullLable()
        {
            return "Full Address Label: \n" + GetFullAddress(); 
        }

    }

    class BaseC { }
```

The above does not work in version 0.1.0 as the **ExampleC.cs** presents the following errors:

```
1>...ExampleC.cs(6,44,6,52): error CS0535: 'ExampleC' does not implement interface member 'IAddress.Address'
1>...ExampleC.cs(6,44,6,52): error CS0535: 'ExampleC' does not implement interface member 'IAddress.City'
1>...ExampleC.cs(6,44,6,52): error CS0535: 'ExampleC' does not implement interface member 'IAddress.State'
1>...ExampleC.cs(6,44,6,52): error CS0535: 'ExampleC' does not implement interface member 'IAddress.ZipCode'
1>...ExampleC.cs(6,44,6,52): error CS0535: 'ExampleC' does not implement interface member 'IAddress.GetAddress()'
```

If I were to change **ExampleC.cs** to include `[AddTrait(AddressTrait)]`, the above errors go away - but then I get the following upon build:

```
SmartTraitsGenerator.PersonalAddressTrait.cs(1,8,1,78): error CS1029: #error: 'only interfaces are allowed for Trait base types, but got AddressTrait'
```

FWIW, I also tried adding `[AddTrait(typeof(AddressTrait))]` to **PersonalAddressTrait** (which also failed miserably):
```csharp
namespace SmartTraits.Tests.Stage4
{
    [Trait]
    [AddTrait(typeof(AddressTrait))]
    abstract partial class PersonalAddressTrait : IName, IAddress
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        [Overrideable]
        public string GetFullName()
        {
            return $"{GetNamePrefix()} {FirstName} {LastName}";
        }

        public string GetFullAddress()
        {
            return $"{GetNamePrefix()} {FirstName} {LastName} \n {Address} \n {City}, {State} \t {ZipCode}";
        }


        [TraitIgnore]
        private string GetNamePrefix()
        {
            return null;
        }
    }
}
```

I have a use case where, on the surface, Trait inheritance (as described here) would be quite useful.  However, before pursuing this further, I thought you might have already considered this and would be aware of any pitfalls or obstacles - or some guidance on how to implement.  

Again, thanks for publishing this!

**Comment by eugenie32b** [comment]
Sorry for delay with the reply.
This project was created as a demo of proof of concept and there were no plans to develop it. 
Especially without pretty much any interest from community.

**Comment by baskren** [comment]
Very understandable.  Your code was a great introduction and saved me a lot of time coming up to speed with Roslyn Source Generators.
